export const REGISTER_CLIENT = 'REGISTER_CLIENT';
export const UPDATE_CLIENTE = 'UPDATE_CLIENTE';
export const CHANGE_OPTION_MENU_DASHBOARD = 'CHANGE_OPTION_MENU_DASHBOARD';
export const LOAD_OPTION_MENU_DASHBOARD = 'LOAD_OPTION_MENU_DASHBOARD'
